[env:teensy41]
platform = https://github.com/tsandmann/platform-teensy.git
board = teensy41
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/tsandmann/FreeRTOS-Teensy.git
build_flags =
    -D USE_TEENSY_HW_SERIAL