image_width: 640
image_height: 480
#camera_name: narrow_stereo
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [552.61214,   0.     , 320.24917,
           0.     , 547.48358, 240.55446,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.130312, -0.221090, 0.002131, -0.001169, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [562.40143,   0.     , 319.11276,   0.     ,
           0.     , 557.07648, 240.78551,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
